apps:
  challenge:
    title:
      en: Challenge
      de: Herausforderung
    description:
      en: Select a challenge and start playing!
      de: W√§hle eine Herausforderung aus und spiele!
  inventory:
    title:
      en: Inventory
      de: Inventar
    description:
      en: Change the skills and resources of your character.
      de: Ver√§ndere die F√§higkeiten und Ressourcen deines Charakters.

items:
  - id: item_1
    type: skill
    ui:
      title:
        en: item_title_1_en
        de: item_title_1_de
      description:
        en: item_description_1_en
        de: item_description_1_de
      icon: üî¶
  - id: item_2
    type: resource
    ui:
      title:
        en: item_title_2_en
        de: item_title_2_de
      description:
        en: item_description_2_en
        de: item_description_2_de
      icon: üî•
  - id: item_3
    type: resource
    ui:
      title:
        en: item_title_3_en
        de: item_title_3_de
      description:
        en: item_description_3_en
        de: item_description_3_de
      icon: üî•
  - id: item_4
    type: resource
    ui:
      title:
        en: item_title_4_en
        de: item_title_4_de
      description:
        en: item_description_4_en
        de: item_description_4_de
      icon: üçΩÔ∏è

characterClasses:
  - id: character_1
    staticItems:
      - item_1
      - item_2
    ui:
      title:
        en: character_title_1_en
        de: character_title_1_de
      description:
        en: character_description_1_en
        de: character_description_1_de
      icon: üßë
  - id: character_2
    staticItems:
      - item_3
      - item_4
    ui:
      title:
        en: character_title_2_en
        de: character_title_2_de
      description:
        en: character_description_2_en
        de: character_description_2_de
      icon: üßõ

challenges:
  - id: challenge_1
    solution:
      - item_1
      - item_2
    ui:
      title:
        en: challenge_title_1_en
        de: challenge_title_1_de
      description:
        en: challenge_description_1_en
        de: challenge_description_1_de
      icon: ‚õ∞Ô∏è
  - id: challenge_2
    solution:
      - item_3
      - item_4
    ui:
      title:
        en: challenge_title_2_en
        de: challenge_title_2_de
      description:
        en: challenge_description_2_en
        de: challenge_description_2_de
      icon: ‚õµ
